#+title: Miryoku ZMK Config

* Overview

This file contains org documentation and ~org-code~ blocks that tangle into the config files required for the ZMK config. Changes to the config should be done in this file, which will then export the config into the proper files.

* Custom Config

This file contains custom miryoku config, including build options and custom layer config.

#+name: custom_config.h
#+begin_src c++ :tangle miryoku/custom_config.h
// ZMK Custom Config

#define MIRYOKU_KLUDGE_SOFT_OFF
#define MIRYOKU_ALPHAS_QWERTY
#define MIRYOKU_CLIPBOARD_WIN

#define XXX &none

// FPS friendly tap layer
// This config is lifted from https://github.com/mnivoliez/miryoku_zmk/blob/master/miryoku/custom_config.h
#define MIRYOKU_LAYER_GAME \
&kp TAB,           &kp Q,             &kp W,             &kp E,             &kp R,             &kp Y,             &kp U,             &kp I,             &kp O,             &kp P,             \
&kp LSHFT,         &kp A,             &kp S,             &kp D,             &kp F,             &kp H,             &kp J,             &kp K,             &kp L,             &kp SQT,           \
&kp LCTRL,         &kp Z,             &kp X,             &kp C,             &kp V,             &kp N,             &kp M,             &kp COMMA,         &kp DOT,           &kp SLASH,         \
U_NP,              U_NP,              &kp LALT,          &kp SPC,           &mo U_GAMENUM,     &kp RET,           &kp BSPC,          &kp DEL,           U_NP,              U_NP

#define MIRYOKU_LAYER_GAMENUM \
&kp ESC,           &kp NUM_1,         &kp NUM_2,         &kp NUM_3,         &kp T,             &kp LBKT,          &kp F7,            &kp F8,            &kp F9,            &kp RBKT,         \
&kp LSHFT,         &kp NUM_4,         &kp NUM_5,         &kp NUM_6,         &kp G,             &kp EQL,           &kp F4,            &kp F5,            &kp F6,            &kp SEMI,         \
&kp LCTRL,         &kp NUM_7,         &kp NUM_8,         &kp NUM_9,         &kp B,             &kp BSLH,          &kp F1,            &kp F2,            &kp F3,            &kp GRAVE,        \
U_NP,              U_NP,              &to U_BASE,        &kp SPC,           &none,             &kp MINUS,         &kp NUM_0,         &kp DOT,           U_NP,              U_NP

// Direct custom layer access
#define MIRYOKU_LAYOUTMAPPING_KYRIA(\
     K00, K01, K02, K03, K04,                          K05, K06, K07, K08, K09, \
     K10, K11, K12, K13, K14,                          K15, K16, K17, K18, K19, \
     K20, K21, K22, K23, K24,                          K25, K26, K27, K28, K29, \
     N30, N31, K32, K33, K34,                          K35, K36, K37, N38, N39 \
)\
XXX  K00  K01  K02  K03  K04                           K05  K06  K07  K08  K09  &to U_GAME  \
XXX  K10  K11  K12  K13  K14                           K15  K16  K17  K18  K19  &to U_BASE  \
XXX  K20  K21  K22  K23  K24  XXX  XXX       XXX  XXX  K25  K26  K27  K28  K29  XXX  \
               XXX  K32  K33  K34  XXX       XXX  K35  K36  K37  XXX

#define MIRYOKU_LAYER_LIST \
MIRYOKU_X(BASE,   "Base") \
MIRYOKU_X(EXTRA,  "Extra") \
MIRYOKU_X(TAP,    "Tap") \
MIRYOKU_X(BUTTON, "Button") \
MIRYOKU_X(NAV,    "Nav") \
MIRYOKU_X(MOUSE,  "Mouse") \
MIRYOKU_X(MEDIA,  "Media") \
MIRYOKU_X(NUM,    "Num") \
MIRYOKU_X(SYM,    "Sym") \
MIRYOKU_X(FUN,    "Fun") \
MIRYOKU_X(GAME,   "Gaming") \
MIRYOKU_X(GAMENUM, "GNum")

#define MIRYOKU_LAYERMAPPING_GAME MIRYOKU_MAPPING
#define MIRYOKU_LAYERMAPPING_GAMENUM MIRYOKU_MAPPING

#define U_BASE   0
#define U_EXTRA  1
#define U_TAP    2
#define U_BUTTON 3
#define U_NAV    4
#define U_MOUSE  5
#define U_MEDIA  6
#define U_NUM    7
#define U_SYM    8
#define U_FUN    9
#define U_GAME   10
#define U_GAMENUM 11
#+end_src

* Kyria Shield Config

These files contain the kconfig options for Zephyr (ZMK).

** Left

Left side of the split keyboard, needed due to right side not supporting WPM reporting.

#+name: kyria_rev2_left
#+begin_src shell :tangle config/kyria_rev2_left.conf
# Display config
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WPM=y
CONFIG_ZMK_WIDGET_WPM_STATUS=y

# RGB underglow config
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y

# Mouse Keys Support
CONFIG_ZMK_POINTING=y

# Soft Off Support
CONFIG_ZMK_PM_SOFT_OFF=y
#+end_src

** Right

Right side of the keyboard, note that WPM config is removed.

#+name: kyria_rev2_right
#+begin_src shell :tangle config/kyria_rev2_right.conf
# Display config
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y

# RGB underglow config
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y

# Mouse Keys Support
CONFIG_ZMK_POINTING=y

# Soft Off Support
CONFIG_ZMK_PM_SOFT_OFF=y
#+end_src

* Building

This section contains more information on building the ~.uf2~ files that are flashed to the micro-controllers.

#+BEGIN_QUOTE
NOTE: If running on ~EvieMacStudio~, the ZMK Build Environment is already setup, however, instructions can be found in [[file:readme.org::*Local Builds][readme.org:Local Builds]], if needed. Alternatively, run the blow source in org-mode.
#+END_QUOTE

#+name: Local Builds
#+begin_src shell :results none :tangle no
cd ~/git/zmk
source .venv/bin/activate
cd ~/git/zmk/app
west build -d build/left -b nice_nano_v2 -- -DSHIELD=kyria_rev2_left -DZMK_CONFIG="/Users/evie/git/miryoku_zmk/config" # Outputs to ~/git/zmk/app/build/left
west build -d build/right -b nice_nano_v2 -- -DSHIELD=kyria_rev2_right -DZMK_CONFIG="/Users/evie/git/miryoku_zmk/config" # Outputs to ~/git/zmk/app/build/right
#+end_src

** Flashing

Once the ~.uf2~ files have been generated, they can be flashed by doing the following:

1. Open ~Finder.app~ and go to ~'~/git/zmk/app/build/[left/right]/zephyr'~
2. Double click the power button on the keyboard half to flash
3. Copy the corresponding ~.uf2~ (left/right) file to the device shown in ~Finder.app~
